
/**
Constructor
Do not call Function in Constructor.
*/
class writePage()
{
	super();

	//TODO:edit here

}
extends AView;


function writePage*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function writePage*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function writePage*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};

function writePage*onCloseBtnClick(comp, info, e)
{

	this.getContainer().close(); 

};
